name: CI/CD Pipeline

on:
  push:
    branches: ["Main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository's code

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Build
        run: npm run build  # Build your Node.js application

      - name: Run tests
        run: npm test  # Run tests if any

      # You can add deployment steps here if needed
